# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/magnus/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/pantech/magnus/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
    vendor/pantech/magnus/proprietary/bin/pantech_server:system/bin/pantech_server \
    vendor/pantech/magnus/proprietary/bin/rild:system/bin/rild \
    vendor/pantech/magnus/proprietary/bin/usb_manager:system/bin/usb_manager \
    vendor/pantech/magnus/proprietary/etc/thermald.conf:system/etc/thermald.conf \
    vendor/pantech/magnus/proprietary/etc/thermald-8064ab.conf:system/etc/thermald-8064ab.conf \
    vendor/pantech/magnus/proprietary/etc/thermald-8960ab.conf:system/etc/thermald-8960ab.conf \
    vendor/pantech/magnus/proprietary/lib/hw/camera.msm8960.so:system/lib/hw/camera.msm8960.so \
    vendor/pantech/magnus/proprietary/lib/hw/nfc.default.so:system/lib/hw/nfc.default.so \
    vendor/pantech/magnus/proprietary/lib/libcamera_client.so:system/lib/libcamera_client.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_imx074_default_video.so:system/lib/libchromatix_imx074_default_video.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_imx074_preview.so:system/lib/libchromatix_imx074_preview.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_imx074_video_hd.so:system/lib/libchromatix_imx074_video_hd.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_imx074_zsl.so:system/lib/libchromatix_imx074_zsl.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_imx091_default_video.so:system/lib/libchromatix_imx091_default_video.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_imx091_preview.so:system/lib/libchromatix_imx091_preview.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_imx091_video_hd.so:system/lib/libchromatix_imx091_video_hd.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_mt9e013_default_video.so:system/lib/libchromatix_mt9e013_default_video.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_mt9e013_preview.so:system/lib/libchromatix_mt9e013_preview.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_mt9e013_video_hfr.so:system/lib/libchromatix_mt9e013_video_hfr.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov2720_default_video.so:system/lib/libchromatix_ov2720_default_video.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov2720_hfr.so:system/lib/libchromatix_ov2720_hfr.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov2720_preview.so:system/lib/libchromatix_ov2720_preview.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov2720_zsl.so:system/lib/libchromatix_ov2720_zsl.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov5647_default_video.so:system/lib/libchromatix_ov5647_default_video.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov5647_preview.so:system/lib/libchromatix_ov5647_preview.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov5647_video_hfr.so:system/lib/libchromatix_ov5647_video_hfr.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov8820_default_video.so:system/lib/libchromatix_ov8820_default_video.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov8820_preview.so:system/lib/libchromatix_ov8820_preview.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov8820_video_hd.so:system/lib/libchromatix_ov8820_video_hd.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov8820_zsl.so:system/lib/libchromatix_ov8820_zsl.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov8825_default_video.so:system/lib/libchromatix_ov8825_default_video.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov8825_preview.so:system/lib/libchromatix_ov8825_preview.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov9726_default_video.so:system/lib/libchromatix_ov9726_default_video.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_ov9726_preview.so:system/lib/libchromatix_ov9726_preview.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_s5k3l1yx_default_video.so:system/lib/libchromatix_s5k3l1yx_default_video.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_s5k3l1yx_hfr_120fps.so:system/lib/libchromatix_s5k3l1yx_hfr_120fps.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_s5k3l1yx_hfr_60fps.so:system/lib/libchromatix_s5k3l1yx_hfr_60fps.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_s5k3l1yx_hfr_90fps.so:system/lib/libchromatix_s5k3l1yx_hfr_90fps.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_s5k3l1yx_preview.so:system/lib/libchromatix_s5k3l1yx_preview.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_s5k3l1yx_video_hd.so:system/lib/libchromatix_s5k3l1yx_video_hd.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_s5k3l1yx_zsl.so:system/lib/libchromatix_s5k3l1yx_zsl.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_s5k4e1_default_video.so:system/lib/libchromatix_s5k4e1_default_video.so \
    vendor/pantech/magnus/proprietary/lib/libchromatix_s5k4e1_preview.so:system/lib/libchromatix_s5k4e1_preview.so \
    vendor/pantech/magnus/proprietary/lib/libgemini.so:system/lib/libgemini.so \
    vendor/pantech/magnus/proprietary/lib/libimage-jpeg-dec-omx-comp.so:system/lib/libimage-jpeg-dec-omx-comp.so \
    vendor/pantech/magnus/proprietary/lib/libimage-jpeg-enc-omx-comp.so:system/lib/libimage-jpeg-enc-omx-comp.so \
    vendor/pantech/magnus/proprietary/lib/libimage-omx-common.so:system/lib/libimage-omx-common.so \
    vendor/pantech/magnus/proprietary/lib/libmmcamera_faceproc.so:system/lib/libmmcamera_faceproc.so \
    vendor/pantech/magnus/proprietary/lib/libmmcamera_frameproc.so:system/lib/libmmcamera_frameproc.so \
    vendor/pantech/magnus/proprietary/lib/libmmcamera_hdr_lib.so:system/lib/libmmcamera_hdr_lib.so \
    vendor/pantech/magnus/proprietary/lib/libmmcamera_image_stab.so:system/lib/libmmcamera_image_stab.so \
    vendor/pantech/magnus/proprietary/lib/libmmcamera_interface2.so:system/lib/libmmcamera_interface2.so \
    vendor/pantech/magnus/proprietary/lib/libmmcamera_statsproc31.so:system/lib/libmmcamera_statsproc31.so \
    vendor/pantech/magnus/proprietary/lib/libmmcamera_wavelet_lib.so:system/lib/libmmcamera_wavelet_lib.so \
    vendor/pantech/magnus/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
    vendor/pantech/magnus/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
    vendor/pantech/magnus/proprietary/lib/libmmstillomx.so:system/lib/libmmstillomx.so \
    vendor/pantech/magnus/proprietary/lib/libmorpho_easy_hdr.so:system/lib/libmorpho_easy_hdr.so \
    vendor/pantech/magnus/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
    vendor/pantech/magnus/proprietary/lib/libOlaEngine.so:system/lib/libOlaEngine.so \
    vendor/pantech/magnus/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/pantech/magnus/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/pantech/magnus/proprietary/vendor/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so
