# Copyright (C) 2014 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/msm8960-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/pantech/msm8960-common/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
    vendor/pantech/msm8960-common/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
    vendor/pantech/msm8960-common/proprietary/bin/btnvtool:system/bin/btnvtool \
    vendor/pantech/msm8960-common/proprietary/bin/cnd:system/bin/cnd \
    vendor/pantech/msm8960-common/proprietary/bin/curl:system/bin/curl \
    vendor/pantech/msm8960-common/proprietary/bin/drmdiagapp:system/bin/drmdiagapp \
    vendor/pantech/msm8960-common/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
    vendor/pantech/msm8960-common/proprietary/bin/efsks:system/bin/efsks \
    vendor/pantech/msm8960-common/proprietary/bin/ftmdaemon:system/bin/ftmdaemon \
    vendor/pantech/msm8960-common/proprietary/bin/ftm_ptt:system/bin/ftm_ptt \
    vendor/pantech/msm8960-common/proprietary/bin/gsiff_daemon:system/bin/gsiff_daemon \
    vendor/pantech/msm8960-common/proprietary/bin/hci_qcomm_init:system/bin/hci_qcomm_init \
    vendor/pantech/msm8960-common/proprietary/bin/ks:system/bin/ks \
    vendor/pantech/msm8960-common/proprietary/bin/mmcblk_utils:system/bin/mmcblk_utils \
    vendor/pantech/msm8960-common/proprietary/bin/mm-pp-daemon:system/bin/mm-pp-daemon \
    vendor/pantech/msm8960-common/proprietary/bin/mpdecision:system/bin/mpdecision \
    vendor/pantech/msm8960-common/proprietary/bin/netmgrd:system/bin/netmgrd \
    vendor/pantech/msm8960-common/proprietary/bin/nl_listener:system/bin/nl_listener \
    vendor/pantech/msm8960-common/proprietary/bin/port-bridge:system/bin/port-bridge \
    vendor/pantech/msm8960-common/proprietary/bin/qcks:system/bin/qcks \
    vendor/pantech/msm8960-common/proprietary/bin/qmiproxy:system/bin/qmiproxy \
    vendor/pantech/msm8960-common/proprietary/bin/qmuxd:system/bin/qmuxd \
    vendor/pantech/msm8960-common/proprietary/bin/qosmgr:system/bin/qosmgr \
    vendor/pantech/msm8960-common/proprietary/bin/qseecomd:system/bin/qseecomd \
    vendor/pantech/msm8960-common/proprietary/bin/quipc_igsn:system/bin/quipc_igsn \
    vendor/pantech/msm8960-common/proprietary/bin/quipc_main:system/bin/quipc_main \
    vendor/pantech/msm8960-common/proprietary/bin/radish:system/bin/radish \
    vendor/pantech/msm8960-common/proprietary/bin/rmt_storage:system/bin/rmt_storage \
    vendor/pantech/msm8960-common/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
    vendor/pantech/msm8960-common/proprietary/bin/thermald:system/bin/thermald \
    vendor/pantech/msm8960-common/proprietary/bin/time_daemon:system/bin/time_daemon \
    vendor/pantech/msm8960-common/proprietary/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
    vendor/pantech/msm8960-common/proprietary/bin/wdsdaemon:system/bin/wdsdaemon \
    vendor/pantech/msm8960-common/proprietary/etc/firmware/vidc_1080p.fw:system/etc/firmware/vidc_1080p.fw \
    vendor/pantech/msm8960-common/proprietary/etc/firmware/vidc.b00:system/etc/firmware/vidc.b00 \
    vendor/pantech/msm8960-common/proprietary/etc/firmware/vidc.b01:system/etc/firmware/vidc.b01 \
    vendor/pantech/msm8960-common/proprietary/etc/firmware/vidc.b02:system/etc/firmware/vidc.b02 \
    vendor/pantech/msm8960-common/proprietary/etc/firmware/vidc.b03:system/etc/firmware/vidc.b03 \
    vendor/pantech/msm8960-common/proprietary/etc/firmware/vidcfw.elf:system/etc/firmware/vidcfw.elf \
    vendor/pantech/msm8960-common/proprietary/etc/firmware/vidc.mdt:system/etc/firmware/vidc.mdt \
    vendor/pantech/msm8960-common/proprietary/etc/OperatorPolicy.xml:system/etc/OperatorPolicy.xml \
    vendor/pantech/msm8960-common/proprietary/etc/qosmgr_rules.xml:system/etc/qosmgr_rules.xml \
    vendor/pantech/msm8960-common/proprietary/etc/UserPolicy.xml:system/etc/UserPolicy.xml \
    vendor/pantech/msm8960-common/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/pantech/msm8960-common/proprietary/lib/hw/sensors.msm8960.so:system/lib/hw/sensors.msm8960.so \
    vendor/pantech/msm8960-common/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
    vendor/pantech/msm8960-common/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
    vendor/pantech/msm8960-common/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
    vendor/pantech/msm8960-common/proprietary/lib/libbson.so:system/lib/libbson.so \
    vendor/pantech/msm8960-common/proprietary/lib/libcneapiclient.so:system/lib/libcneapiclient.so \
    vendor/pantech/msm8960-common/proprietary/lib/libcnefeatureconfig.so:system/lib/libcnefeatureconfig.so \
    vendor/pantech/msm8960-common/proprietary/lib/libcneqmiutils.so:system/lib/libcneqmiutils.so \
    vendor/pantech/msm8960-common/proprietary/lib/libcneutils.so:system/lib/libcneutils.so \
    vendor/pantech/msm8960-common/proprietary/lib/libCommandSvc.so:system/lib/libCommandSvc.so \
    vendor/pantech/msm8960-common/proprietary/lib/libconfigdb.so:system/lib/libconfigdb.so \
    vendor/pantech/msm8960-common/proprietary/lib/libcurl.so:system/lib/libcurl.so \
    vendor/pantech/msm8960-common/proprietary/lib/libdiag.so:system/lib/libdiag.so \
    vendor/pantech/msm8960-common/proprietary/lib/libDivxDrm.so:system/lib/libDivxDrm.so \
    vendor/pantech/msm8960-common/proprietary/lib/libdrmdiag.so:system/lib/libdrmdiag.so \
    vendor/pantech/msm8960-common/proprietary/lib/libdrmfs.so:system/lib/libdrmfs.so \
    vendor/pantech/msm8960-common/proprietary/lib/libdrmtime.so:system/lib/libdrmtime.so \
    vendor/pantech/msm8960-common/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
    vendor/pantech/msm8960-common/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so \
    vendor/pantech/msm8960-common/proprietary/lib/libdss.so:system/lib/libdss.so \
    vendor/pantech/msm8960-common/proprietary/lib/libdsucsd.so:system/lib/libdsucsd.so \
    vendor/pantech/msm8960-common/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
    vendor/pantech/msm8960-common/proprietary/lib/libgps.so:system/lib/libgps.so \
    vendor/pantech/msm8960-common/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
    vendor/pantech/msm8960-common/proprietary/lib/libidl.so:system/lib/libidl.so \
    vendor/pantech/msm8960-common/proprietary/lib/libiw.so:system/lib/libiw.so \
    vendor/pantech/msm8960-common/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
    vendor/pantech/msm8960-common/proprietary/lib/libloc_api_v02.so:system/lib/libloc_api_v02.so \
    vendor/pantech/msm8960-common/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
    vendor/pantech/msm8960-common/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
    vendor/pantech/msm8960-common/proprietary/lib/libmm-abl-oem.so:system/lib/libmm-abl-oem.so \
    vendor/pantech/msm8960-common/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
    vendor/pantech/msm8960-common/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
    vendor/pantech/msm8960-common/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
    vendor/pantech/msm8960-common/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
    vendor/pantech/msm8960-common/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
    vendor/pantech/msm8960-common/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
    vendor/pantech/msm8960-common/proprietary/lib/libpantech_qcci.so:system/lib/libpantech_qcci.so \
    vendor/pantech/msm8960-common/proprietary/lib/libpantech_wifi_mac_backup.so:system/lib/libpantech_wifi_mac_backup.so \
    vendor/pantech/msm8960-common/proprietary/lib/libpantech_wifi_mac_rw.so:system/lib/libpantech_wifi_mac_rw.so \
    vendor/pantech/msm8960-common/proprietary/lib/libpkm.so:system/lib/libpkm.so \
    vendor/pantech/msm8960-common/proprietary/lib/libqcci_legacy.so:system/lib/libqcci_legacy.so \
    vendor/pantech/msm8960-common/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
    vendor/pantech/msm8960-common/proprietary/lib/libqdi.so:system/lib/libqdi.so \
    vendor/pantech/msm8960-common/proprietary/lib/libqdp.so:system/lib/libqdp.so \
    vendor/pantech/msm8960-common/proprietary/lib/libqmi_cci.so:system/lib/libqmi_cci.so \
    vendor/pantech/msm8960-common/proprietary/lib/libqmi_client_qmux.so:system/lib/libqmi_client_qmux.so \
    vendor/pantech/msm8960-common/proprietary/lib/libqmi_common_so.so:system/lib/libqmi_common_so.so \
    vendor/pantech/msm8960-common/proprietary/lib/libqmi_csi.so:system/lib/libqmi_csi.so \
    vendor/pantech/msm8960-common/proprietary/lib/libqmi_csvt_srvc.so:system/lib/libqmi_csvt_srvc.so \
    vendor/pantech/msm8960-common/proprietary/lib/libqmi_encdec.so:system/lib/libqmi_encdec.so \
    vendor/pantech/msm8960-common/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
    vendor/pantech/msm8960-common/proprietary/lib/libqmi.so:system/lib/libqmi.so \
    vendor/pantech/msm8960-common/proprietary/lib/libQSEEComAPI.so:system/lib/libQSEEComAPI.so \
    vendor/pantech/msm8960-common/proprietary/lib/libquipc_os_api.so:system/lib/libquipc_os_api.so \
    vendor/pantech/msm8960-common/proprietary/lib/libquipc_ulp_adapter.so:system/lib/libquipc_ulp_adapter.so \
    vendor/pantech/msm8960-common/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
    vendor/pantech/msm8960-common/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
    vendor/pantech/msm8960-common/proprietary/lib/libsensor1.so:system/lib/libsensor1.so \
    vendor/pantech/msm8960-common/proprietary/lib/libsensor_reg.so:system/lib/libsensor_reg.so \
    vendor/pantech/msm8960-common/proprietary/lib/libsky_psttransmit.so:system/lib/libsky_psttransmit.so \
    vendor/pantech/msm8960-common/proprietary/lib/libsky_rawdata.so:system/lib/libsky_rawdata.so \
    vendor/pantech/msm8960-common/proprietary/lib/libskytestclient.so:system/lib/libskytestclient.so \
    vendor/pantech/msm8960-common/proprietary/lib/libsnsutils.so:system/lib/libsnsutils.so \
    vendor/pantech/msm8960-common/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
    vendor/pantech/msm8960-common/proprietary/lib/libulp2.so:system/lib/libulp2.so \
    vendor/pantech/msm8960-common/proprietary/lib/libulp.so:system/lib/libulp.so \
    vendor/pantech/msm8960-common/proprietary/lib/libwcnftmpscan.so:system/lib/libwcnftmpscan.so \
    vendor/pantech/msm8960-common/proprietary/lib/libwcnftmp.so:system/lib/libwcnftmp.so \
    vendor/pantech/msm8960-common/proprietary/lib/libwifiscanner.so:system/lib/libwifiscanner.so \
    vendor/pantech/msm8960-common/proprietary/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so \
    vendor/pantech/msm8960-common/proprietary/lib/libxml.so:system/lib/libxml.so \
    vendor/pantech/msm8960-common/proprietary/lib/libyas530.so:system/lib/libyas530.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/drm/libdrmwvmplugin.so:system/vendor/lib/drm/libdrmwvmplugin.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/hw/power.qcom.so:system/vendor/lib/hw/power.qcom.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libwvm.so:system/vendor/lib/libwvm.so \
    vendor/pantech/msm8960-common/proprietary/vendor/lib/libWVStreamControlAPI_L3.so:system/vendor/lib/libWVStreamControlAPI_L3.so
